import '../globals.css';
import Footer from './_components/footer';
import { Navbar } from "./_components/navbar"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="h-full bg-slate-100">
          <Navbar/>
          <main className="pt-40 pb-20 bg-slate-100">
            {children}
          </main>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
